apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: task-tracker
data:
  PRIMARY_DATABASE_URL: "postgres://postgres:postgres@pg-svc.task-tracker/analytics_development" # <- pg-svc is the name of the service that exposes the Postgres pod
  AUTH_DATABASE_PASSWORD: ''
  RAILS_ENV: "development"
  RAILS_LOG_TO_STDOUT: "true"
  AUTH_APP_PRIVATE_URL: 'auth-svc.task-tracker.svc.cluster.local:3000'
  AUTH_APP_PUBLIC_URL: 'localhost:31000'
  KAFKA_URL: 'kafka-broker:9092'
