kind: Secret
apiVersion: v1
metadata:
  name: analytics-secrets
  namespace: task-tracker
type: Opaque
data:
  AUTH_KEY: Q1hieGU4ZGttQS1yb0hhWXF2dlVkS2UxQkZ6QVY1ZzljTXc5VmJWR3ZwWQ== # <- base64 encoded uid from OAuth
  AUTH_SECRET: MGwwODZWZmI1YkNRVXdZcmdzQUxEcEM0c19RVWJRVWtWMlRjZzdnYjRxSQ== # <- base64 encoded from OAuth
