apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracking-deployment
  labels: # must match the service
    app: task-tracking
  namespace: task-tracker
spec:
  replicas: 1
  selector:
    matchLabels: # which pods are we deploying
      app: task-tracking
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels: # must match service and replicaset matchlabel
        app: task-tracking
    spec:
      hostAliases:
        - ip: "10.96.0.16" # clusterIP of kafka service
          hostnames:
          - "kafka-broker"
      containers:
      - name: task-tracking
        image: task_tracking
        imagePullPolicy: Never # use local docker image
        resources:
          requests:
            cpu: 500m
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: task-tracking-config
          - secretRef:
              name: task-tracking-secrets
        readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
