kind: Service
apiVersion: v1
metadata:
  name: task-tracking-svc
  namespace: task-tracker
spec:
  selector:
    app: task-tracking
  type: NodePort
  #type: LoadBalancer on AWS
  ports:
    - name: http
      protocol: TCP
      # port exposed by the service
      port: 5000
      # the port the app is listening on targetPort
      targetPort: 5000
      nodePort: 30004
