apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels: # must match the service
    app: auth
  namespace: task-tracker
spec:
  replicas: 1
  selector:
    matchLabels: # which pods are we deploying
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels: # must match service and replicaset matchlabel
        app: auth
    spec:
      hostAliases:
        - ip: "10.96.0.16" # clusterIP of kafka service
          hostnames:
          - "kafka-broker"
      containers:
      - name: auth
        image: auth
        imagePullPolicy: Never # use local docker image
        resources:
          requests:
            cpu: 500m
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: auth-config
        readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
