apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: task-tracker
data:
  PRIMARY_DATABASE_URL: "postgres://postgres:postgres@pg-svc.task-tracker/auth_development" # <- pg-svc is the name of the service that exposes the Postgres pod
  AUTH_DATABASE_PASSWORD: ''
  RAILS_ENV: "development"
  RAILS_LOG_TO_STDOUT: "true"
