kind: Service
apiVersion: v1
metadata:
  name: auth-svc
  namespace: task-tracker
spec:
  selector:
    app: auth
  type: NodePort
  #type: LoadBalancer on AWS
  ports:
    - name: http
      protocol: TCP
      # port exposed by the service
      port: 3000
      # the port the app is listening on targetPort
      targetPort: 3000
