kind: Secret
apiVersion: v1
metadata:
  name: task-tracker-secrets
  namespace: task-tracker
type: Opaque
data:
  AUTH_KEY: UEtyRlYtT3ZwYkIxaHNHWC1YRHVNNFdlSUFZbDRDUk1wekdRN3dCYU1BMA== # <- base64 encoded uid from OAuth
  AUTH_SECRET: SjJvQ2lVMzRiSEhYalBFc1RUUEZtc2VDdXh0VWhyMFE2akMyTWFzcFFMaw== # <- base64 encoded from OAuth
