kind: Secret
apiVersion: v1
metadata:
  name: billing-secrets
  namespace: task-tracker
type: Opaque
data:
  AUTH_KEY: Q0NpSkJxVmlJN0o0TTZfYlRNa3JXWHJsclYzUlN0aGMwT0pZWk5LU0JlZw== # <- base64 encoded uid from OAuth
  AUTH_SECRET: SUQ2UnNpOWdKZV9UUTNza2tKLVhqa1JmUTN3aDk1cGFTc2hBUE5jSThwaw== # <- base64 encoded from OAuth
