kind: Service
apiVersion: v1
metadata:
  name: billing-svc
  namespace: task-tracker
spec:
  selector:
    app: billing
  type: NodePort
  #type: LoadBalancer on AWS
  ports:
    - name: http
      protocol: TCP
      # port exposed by the service
      port: 4000
      # the port the app is listening on targetPort
      targetPort: 4000
      nodePort: 30003
