apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: task-tracker
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181 # is nodePort needed?
      targetPort: 2181
  selector:
    app: zookeeper # should match deployment label
