apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: task-tracker
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper # should match deployment label
